kind: ConfigMap
apiVersion: v1
metadata:
  name: tbs-trades-crawler
  labels:
    name: tbs-trades-crawler
    instance: tbs-trades-crawler
data:
  VERSION: "0.0.1"
  MONGO_CONNECTION_STRING: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Tbs Trades Crawler"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  SPLUNK_HOST: "log.tech1a.co"
  SPLUNK_PORT: "5141"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbs-trades-crawler
spec:
  selector:
    matchLabels:
      app: tbs-trades-crawler
  replicas: 1
  template:
    metadata:
      labels:
        app: tbs-trades-crawler
    spec:
      containers:
      - name: tbs-trades-crawler
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/tbs-trades-crawler:latest"
        envFrom:
          - configMapRef:
              name: tbs-trades-crawler
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tbs-trades-crawler
  labels:
    app: tbs-trades-crawler
spec:
  type: ClusterIP
  selector:
    app: tbs-trades-crawler
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tbs-trades-crawler
spec:
  ingressClassName: nginx
  rules:
    - host: devtbs-trades-crawler.tech1a.co
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tbs-trades-crawler
              port:
                number: 80

