variables:
    IMAGE_NAME: tbs-trades-crawler
    IMAGE_TAG_PID: $CI_PIPELINE_ID 
    IMAGE_TAG_TAG: $CI_COMMIT_TAG          
    SMS_MESSAGE_BUILD: $IMAGE_NAME-->Build-OK
    SMS_MESSAGE_Deploy_Dev: $IMAGE_NAME-->Deployed->Develop
    SMS_MESSAGE_Deploy_Stg: $IMAGE_NAME-->Deployed->Stage
    SMS_MESSAGE_Deploy_Pro: $IMAGE_NAME-->Deployed->Production
    REGISTRY_HOST: $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT
    NAMESPACE_Dev: dev-marketer
    NAMESPACE_Stg: stg-marketer
    NAMESPACE_Pro: pro-marketer

stages:
  - Code Quality
  - Build
  - Build SMS Notifications
  - Deploy Dev
  - Deploy Dev Notifications
  - Deploy Staging
  - Deploy Stg Notifications
  - Deploy Production
  - Deploy Pro Notifications

sonarqube-analysis:
  stage: Code Quality
  image: 
    name: $REGISTRY_HOST/repository/tools/sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  #only:
    #- master
  retry: 2

###############################################################################################
#########                                                                             #########
#########                                   Build                                       #########
#########                                                                             #########
###############################################################################################


build:
    stage: Build
    image: $REGISTRY_HOST/repository/tech1a-docker-registry/docker:20.10.17
    services:
    - name: $REGISTRY_HOST/repository/tech1a-docker-registry/docker:20.10.17-dind
      alias: docker
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
    variables:
      DOCKER_DAEMON_OPTIONS: "--insecure-registry=$REGISTRY_HOST"
    script:
        - docker login -u "$DOCKER_PRIVATE_REGISTRY_USER" -p "$DOCKER_PRIVATE_REGISTRY_PASSWORD" "http://$REGISTRY_HOST"
        - docker build  --build-arg  DOCKER_PRIVATE_REGISTRY_PASSWORD=$DOCKER_PRIVATE_REGISTRY_PASSWORD -t $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest .
        - docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest
        - docker tag $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_PID
        - docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_PID
        - (if [ "$CI_COMMIT_TAG" != "" ]; then docker tag $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_TAG;docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_TAG; fi);
        #- docker tag $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_TAG
        #- docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_TAG
 
    after_script:
        -  echo "Build succeeded"
build-SMS:
  stage: Build SMS Notifications
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/curlimages/curl
  script:
    - curl -X POST "https://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup&body=$SMS_MESSAGE_BUILD&flash=0"
  needs:
    - job: build

###############################################################################################
#########                                                                             #########
#########                                   Deploy Develop                            #########
#########                                                                             #########
###############################################################################################
deploy-dev:
  stage: Deploy Dev
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/dtzar/helm-kubectl:3.0.3
  script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$K8S_STG" | base64 -d > ~/.kube/config
    - kubectl -n "$NAMESPACE_Dev" apply -f deployment/dev/dev.yaml
    - kubectl set image -n "$NAMESPACE_Dev" deployment/$IMAGE_NAME $IMAGE_NAME=$REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_PID
  needs:
    - job: build
  retry: 2
  only:
    - dev

deploy-dev-SMS:
  stage: Deploy Dev Notifications
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/curlimages/curl
  script:
    - curl -X POST "https://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup&body=$SMS_MESSAGE_Deploy_Dev&flash=0"
  needs:
    - job: deploy-dev
  only:
    - dev

###############################################################################################
#########                                                                             #########
#########                                   Deploy Staging                            #########
#########                                                                             #########
###############################################################################################

deploy-staging:
  stage: Deploy Staging
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/dtzar/helm-kubectl:3.0.3
  script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$K8S_STG" | base64 -d > ~/.kube/config
    - kubectl -n "$NAMESPACE_Stg" apply -f deployment/stage/stage.yaml
    - kubectl set image -n "$NAMESPACE_Stg" deployment/$IMAGE_NAME $IMAGE_NAME=$REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_PID
  needs:
    - job: build
  retry: 2
  only:
    - stg



deploy-stg-SMS:
  stage: Deploy Stg Notifications
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/curlimages/curl
  script:
    - curl -X POST "https://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup&body=$SMS_MESSAGE_Deploy_Stg&flash=0"
  needs:
    - job: deploy-staging
  only:
    - stg


###############################################################################################
#########                                                                             #########
#########                                 Deploy Production                           #########
#########                                                                             #########
###############################################################################################

deploy-pro:
  stage: Deploy Production
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/dtzar/helm-kubectl:3.0.3
  script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$K8S_PRO" | base64 -d > ~/.kube/config
    - kubectl -n "$NAMESPACE_Pro" apply -f deployment/pro/pro.yaml
    - kubectl set image -n "$NAMESPACE_Pro" deployment/$IMAGE_NAME $IMAGE_NAME=$REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$IMAGE_TAG_TAG
  needs:
    - job: build
  retry: 2
  only:
    - tags
  when: manual

deploy-pro-SMS:
  stage: Deploy Pro Notifications
  image: $REGISTRY_HOST/repository/tech1a-docker-registry/curlimages/curl
  script:
    - curl -X POST "https://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup&body=$SMS_MESSAGE_Deploy_Pro&flash=0"
  needs:
    - job: deploy-pro
  only:
    - tags

