kind: ConfigMap
apiVersion: v1
metadata:
  name: tbs-trades-crawler
  labels:
    name: tbs-trades-crawler
    instance: tbs-trades-crawler
data:
  VERSION: "0.0.1"
  MONGO_CONNECTION_STRING: "mongodb://root:1219S4OiIhSXPJmOGfmdlFlsQ121@mongo-marketer-headless.pro-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Tbs Trades Crawler"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  ISSUER: "https://idp.tavanabroker.ir"
  SPLUNK_HOST: "log.tech1a.co"
  SPLUNK_PORT: "6141"
  FASTAPI_DOCS: "/docs"
  FASTAPI_REDOC: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbs-trades-crawler
spec:
  selector:
    matchLabels:
      app: tbs-trades-crawler
  replicas: 1
  template:
    metadata:
      labels:
        app: tbs-trades-crawler
    spec:
      containers:
      - name: tbs-trades-crawler
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/tbs-trades-crawler:latest"
        envFrom:
          - configMapRef:
              name: tbs-trades-crawler
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tbs-trades-crawler
  labels:
    app: tbs-trades-crawler
spec:
  type: ClusterIP
  selector:
    app: tbs-trades-crawler
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tbs-trades-crawler
  annotations:
    nginx.ingress.kubernetes.io/server-alias: "tbs-trades-crawler.tavanaco.ir"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,178.252.0.0/16,172.23.0.0/16,172.24.0.0/16,172.252.189.224/29"
    nginx.org/server-snippets: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    -  tbs-trades-crawler.tavanaco.ir
    secretName: tavanaco-ir
  rules:
    - host: tbs-trades-crawler.tavanaco.ir
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tbs-trades-crawler
              port:
                number: 443

